name: SixthSensePhoto
favicon: null
layout_spectrum: 0.26598
typography_spectrum: 0.16404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4281c4'
    - '#f68122'
    - '#f04730'
    - '#a5c1e0'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
